package vbs.vvi.com.bs.db;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dBUserBeanDaoConfig;

    private final DBUserBeanDao dBUserBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dBUserBeanDaoConfig = daoConfigMap.get(DBUserBeanDao.class).clone();
        dBUserBeanDaoConfig.initIdentityScope(type);

        dBUserBeanDao = new DBUserBeanDao(dBUserBeanDaoConfig, this);

        registerDao(DBUserBean.class, dBUserBeanDao);
    }
    
    public void clear() {
        dBUserBeanDaoConfig.getIdentityScope().clear();
    }

    public DBUserBeanDao getDBUserBeanDao() {
        return dBUserBeanDao;
    }

}
